title: Curso de Treinador de Cães
description: Conteúdo informativo sobre vários aspectos dos canídeos
author:
  name: Oscar FM
  email: i00nsu@duck.com
theme: minima
minima: 
  skin: dark
  social_links: 
    - { platform: github, user_url: "https://github.com/MacacoBudista" }
show_downloads: false

